# the touchpad TOS01f6 on allium is not yet fully supported by the synaptics driver
# (even though I'm writing this in 2026 and a patch existed almost 8 months ago)
# https://marc.info/?l=linux-input&m=174279100829351&w=2
options psmouse synaptics_intertouch=1
